- name: Configure reverse-proxy to Tomcat
  hosts: Webservers
  become: true

  tasks:
    - name: Deactivate the default nginx site
      file:
         path: /etc/nginx/sites-enabled/default
         state: absent

    - name: Generate the reverse-proxy site config
      template:
        src: reverse-proxy.conf
        dest: /etc/nginx/sites-available/

    - name: Activate the reverse-proxy site config
      file: 
        src: /etc/nginx/sites-available/reverse-proxy.conf
        dest: /etc/nginx/sites-enabled/reverse-proxy.conf
        state: link

    - name: Start NGiNX
      service:
         name: nginx
         state: restarted
